//
// Generated file, do not edit! Created by opp_msgc 4.2 from src/networklayer/arp/ARPPacketRoute.msg.
//

#ifndef _ARPPACKETROUTE_M_H_
#define _ARPPACKETROUTE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "IPv4Address.h"
#include "MACAddress.h"


#define ARP_HEADER_BYTES   28
// }}



/**
 * Enum generated from <tt>src/networklayer/arp/ARPPacketRoute.msg</tt> by opp_msgc.
 * <pre>
 * enum ARPRouteOpcode
 * {
 * 
 *     ARP_REQUEST = 1;      
 *     ARP_REPLY = 2;        
 *     ARP_RARP_REQUEST = 3; 
 *     ARP_RARP_REPLY = 4;   
 * }
 * </pre>
 */
enum ARPRouteOpcode {
    ARP_REQUEST = 1,
    ARP_REPLY = 2,
    ARP_RARP_REQUEST = 3,
    ARP_RARP_REPLY = 4
};

/**
 * Class generated from <tt>src/networklayer/arp/ARPPacketRoute.msg</tt> by opp_msgc.
 * <pre>
 * packet ARPPacketRoute
 * {
 *     int opcode enum(ARPRouteOpcode);
 *     MACAddress srcMACAddress;
 *     MACAddress destMACAddress;
 *     IPv4Address srcIPAddress;
 *     IPv4Address destIPAddress;
 *     
 *     string route; 
 * }
 * </pre>
 */
class ARPPacketRoute : public ::cPacket
{
  protected:
    int opcode_var;
    MACAddress srcMACAddress_var;
    MACAddress destMACAddress_var;
    IPv4Address srcIPAddress_var;
    IPv4Address destIPAddress_var;
    opp_string route_var;

  private:
    void copy(const ARPPacketRoute& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ARPPacketRoute&);

  public:
    ARPPacketRoute(const char *name=NULL, int kind=0);
    ARPPacketRoute(const ARPPacketRoute& other);
    virtual ~ARPPacketRoute();
    ARPPacketRoute& operator=(const ARPPacketRoute& other);
    virtual ARPPacketRoute *dup() const {return new ARPPacketRoute(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getOpcode() const;
    virtual void setOpcode(int opcode);
    virtual MACAddress& getSrcMACAddress();
    virtual const MACAddress& getSrcMACAddress() const {return const_cast<ARPPacketRoute*>(this)->getSrcMACAddress();}
    virtual void setSrcMACAddress(const MACAddress& srcMACAddress);
    virtual MACAddress& getDestMACAddress();
    virtual const MACAddress& getDestMACAddress() const {return const_cast<ARPPacketRoute*>(this)->getDestMACAddress();}
    virtual void setDestMACAddress(const MACAddress& destMACAddress);
    virtual IPv4Address& getSrcIPAddress();
    virtual const IPv4Address& getSrcIPAddress() const {return const_cast<ARPPacketRoute*>(this)->getSrcIPAddress();}
    virtual void setSrcIPAddress(const IPv4Address& srcIPAddress);
    virtual IPv4Address& getDestIPAddress();
    virtual const IPv4Address& getDestIPAddress() const {return const_cast<ARPPacketRoute*>(this)->getDestIPAddress();}
    virtual void setDestIPAddress(const IPv4Address& destIPAddress);
    virtual const char * getRoute() const;
    virtual void setRoute(const char * route);
};

inline void doPacking(cCommBuffer *b, ARPPacketRoute& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ARPPacketRoute& obj) {obj.parsimUnpack(b);}


#endif // _ARPPACKETROUTE_M_H_
